spring:
  profiles:
    active: "local"
    group:
      local: "mangurl-local"
---
spring:
  config:
    activate:
      on-profile: "mangurl-local"
    import:
      - "classpath:mangurl/local.yml"
