spring:
  profiles:
    active: "local"
    group:
      local:
        - "mangurl-local"
      local-container:
        - "mangurl-local"
        - "mangurl-local-container"
      test:
        - "mangurl-test"
      dev:
        - "mangurl-dev"
      prod:
        - "mangurl-prod"
springdoc:
  api-docs:
    path: "/api/docs"
  swagger-ui:
    path: "/api/docs.html"
---
spring:
  config:
    activate:
      on-profile: "mangurl-local"
    import:
      - "classpath:mangurl/local.yml"
---
spring:
  config:
    activate:
      on-profile: "mangurl-local-container"
    import:
      - "classpath:mangurl/local-container.yml"
---
spring:
  config:
    activate:
      on-profile: "mangurl-test"
    import:
      - "optional:classpath:mangurl/test.yml"
---
spring:
  config:
    activate:
      on-profile: "mangurl-dev"
    import:
      - "classpath:mangurl/dev.yml"
---
spring:
  config:
    activate:
      on-profile: "mangurl-prod"
    import:
      - "optional:classpath:mangurl/prod.yml"
