spring:
  profiles:
    active: "local"
    group:
      local:
        - "mangurl-local"
      local-container:
        - "mangurl-local"
        - "mangurl-local-container"
      test:
        - "mangurl-test"
      dev:
        - "mangurl-dev"
      prod:
        - "mangurl-prod"
---
spring:
  config:
    activate:
      on-profile: "mangurl-local"
    import:
      - "classpath:mangurl/local.yml"
---
spring:
  config:
    activate:
      on-profile: "mangurl-local-container"
    import:
      - "classpath:mangurl/local-container.yml"
---
spring:
  config:
    activate:
      on-profile: "mangurl-test"
    import:
      - "classpath:mangurl/test.yml"
---
spring:
  config:
    activate:
      on-profile: "mangurl-dev"
    import:
      - "classpath:mangurl/dev.yml"
---
spring:
  config:
    activate:
      on-profile: "mangurl-prod"
    import:
      - "classpath:mangurl/prod.yml"
