name: "mangurl"
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: "mangurl-dynamodb"
    ports:
      - "8000:8000"
  mangurl:
    depends_on:
      - "dynamodb-local"
    image: "mangurl:latest"
    container_name: "mangurl"
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Dfile.encoding=UTF-8"
      SPRING_PROFILES_ACTIVE: "local-container"
